# Generated by Django 3.1.6 on 2021-02-15 06:13

import contatos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=54)),
                ('name', models.CharField(max_length=255)),
                ('number_tel', models.CharField(max_length=54)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=contatos.models.upload)),
                ('favorited', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
